# Programming Assignment 1: Python Tutorial

Credits: This notebook is inspired by a [Python tutorial](http://cs231n.github.io/python-numpy-tutorial/) by [Justin Johnson](https://web.eecs.umich.edu/~justincj/) for [CS231n](http://cs231n.github.io/).

Feel free to refer to the original course for more practice.

## Introduction

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

In this tutorial, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images
* IPython: Creating notebooks, Typical workflows

<h3>Assignment Instructions - Read Carefully</h3>

* **How to install 'otter'**: Run `pip install otter-grader` in your Anaconda Command Prompt
* **Otter**: It is an autograder that we will be using for grading your notebooks.
* **Initialize Otter**: Run the cell above to initialize otter.
* **grader.check('qn')**: This command runs test cases for nth question `qn` provided to you and displays the result. But these are not the only test cases, these are provided just for your basic testing. There will be some *hidden test cases* on which your answers will be tested as well.
* You are **not** allowed to edit any pre-defined variables and as per the instructions for every question you have to assign your answers to these variables.
* Write your answers in place of `...`
* For auto-graded questions, the marking will be binary. There is NO partial marking.
* Make sure all your graphs are labelled and annotated correctly. Not doing so will incur a penalty.

<h3>Submission Instructions - Read Carefully </h3>

* You must submit this notebook file only and it must not has any folder or any other file. 
* The name of this file must be `PA0_RollNumber`. For example if your roll number is `26100053` it should be `PA0_26100053`. 


Please run the cell below to initialize the autograder. Your assignment will NOT be graded otherwise.

In [1]:
import otter
grader = otter.Notebook()

## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [6]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

[1, 1, 2, 3, 6, 8, 10]


### Python versions

For this class all code will use Python 3.7. You can check your Python version by executing the cell below:

In [7]:
!python --version

Python 3.13.5


### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [8]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"

<class 'int'>
3


In [9]:
y = x + 1
print(y)   # Addition; prints "4"
y = x - 1
print(y)   # Subtraction; prints "2"
y = x * 2
print(y)   # Multiplication; prints "6"
y = x ** 2
print(y)   # Exponentiation; prints "9"


4
2
6
9


In [10]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [11]:
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [12]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


#### Strings

Python has great support for strings:

In [13]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


String objects have a bunch of useful methods; for example:

In [14]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [15]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

##### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [16]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


##### Loops

You can loop over the elements of a list like this:

In [17]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [18]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


##### List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [19]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [20]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [21]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [22]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#dict).

##### Loops

It is easy to iterate over the keys in a dictionary:

In [23]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the `items` method:

In [24]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


##### Dictionary comprehensions

These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [25]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [26]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


As usual, everything you want to know about sets can be found in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#set).

##### Loops

Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [27]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: cat", "#3: dog"

#1: cat
#2: dog
#3: fish


##### Set comprehensions

Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [28]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [29]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


The [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#tuples-and-sequences) has more information about tuples.

### Functions

Python functions are defined using the `def` keyword. For example:

In [30]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [31]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


There is a lot more information about Python functions in the [documentation](https://docs.python.org/3.7/tutorial/controlflow.html#defining-functions).

#### Lambda Functions
These are anonymous functions in Python which take any number of arguments but only one expression. Syntax:
`lambda arguments : expression`. They are one line function and expression are representing the body of a normal function.

In [32]:
l = lambda a : a+5  ## lambda function 'l' is created which is taking 'a' as an argument and expression adds 5 to the value of argument a
print(l(2))  ## passing 2 as value of 'a' argument of lambda function 'l' . This will return 7(7 = 2+5) as output.

l1 = lambda a,b,c : a * b * c ## lambda function 'l1' is created which is taking 3 arguments (a,b,c) and return the result by multiplying them all.
print(l1(10,20,30))  ## passing 10,20,30 as arguments 'a', 'b', 'c' respectively to 'l1' function. Print result 6000 (6000 = 10*20*30)

7
6000


We can use Lambda function anonymously inside other functions. Example is shown below

In [33]:
def func(n):  ## define a function that takes argument 'n' and returns a lambda function after multiplying some unknown argument 'a' with given 'n'
  return lambda a: a*n

l2 = func(4)  ## passing 4 as value of 'n' in 'func' function. This will return lambda function 'l2' where n is assigned a value of 4.
print(l2(6)) ## This will call lambda function 'l2' where 6 is given as value for argument 'a'. Print 24(24 = 6*4) as result

24


### Classes

The syntax for defining classes in Python is straightforward:

In [34]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


You can read a lot more about Python classes in the [documentation](https://docs.python.org/3.7/tutorial/classes.html).

## Numpy

[Numpy](https://numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [35]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [36]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [37]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.20122107 0.21479141]
 [0.46992761 0.25116078]]


You can read about other methods of array creation in the [documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

### Array indexing

Numpy offers several ways to index into arrays.

#### Slicing

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [38]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array:

In [39]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Integer array indexing

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [40]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [41]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [42]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [43]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


You can read all about numpy datatypes in the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [44]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [45]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [46]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [47]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Numpy provides many more functions for manipulating arrays; you can see the full list in the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [48]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [49]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`. Consider this version, using broadcasting:

In [50]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](https://numpy.org/devdocs/user/theory.broadcasting.html).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [51]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## Iterators

Iterators are objects that contain countable number of values. Iterators can traverse the different structures like list, dictionaries, tuples, strings and sets etc through their values. The structures on which iterators can iterate on are called **iterable objects**. For example, we will make a list and return iterator from it.The `next()` function on iterator is called to get the next item from iterator.

In [52]:
mylist = ['blue', 'orange', 'green', 'yellow']  ## create a list 'mylist'
itr = iter(mylist)  ## create an iterator of mylist using iter() function
print(next(itr))  ## print 1st element of mylist
print(next(itr))  ## print 2nd element of mylist
print(next(itr))  ## print 3rd element of mylist
print(next(itr))  ## print 4rth element of mylist

blue
orange
green
yellow


## Zip in Python
Zip function returns a zip object which is an iterator of tuples where first tuple represent the first enteries of the two passed tuples paired together, second tuple represents the second entries of passed tuples paired together and so on.
Example below shows two tuples `a` and `b` passed as input to `zip` function to zip respective entries together.


In [53]:
a = ('2', '3', '4', '5', '6')  ## create tuple 'a'
b = ('4', '9', '16', '25', '36')  ## create b tuple 'b'
z = zip(a,b) ## zip both tuples
print(tuple(z)) ## print zip result. Will print (('2', '4'), ('3', '9'), ('4', '16'), ('5', '25'), ('6', '36'))

(('2', '4'), ('3', '9'), ('4', '16'), ('5', '25'), ('6', '36'))


### Zip Lists

Zip can also be used to zip entries of two lists together. Example is given below:

In [54]:
a = ['l1', 'l2', 'l3', 'l4', 'l5'] ## create list 'a'
b = ['s1', 's2', 's3', 's4', 's5'] ## create tuple 'b'
z = zip(a,b) ## zip both lists
print(list(z))## print zip result. Will print [('l1', 's1'), ('l2', 's2'), ('l3', 's3'), ('l4', 's4'), ('l5', 's5')]

[('l1', 's1'), ('l2', 's2'), ('l3', 's3'), ('l4', 's4'), ('l5', 's5')]


### Zip Lists to a dictionary
We can zip entries of two lists together to form a dictionary. Given an example below use `zip` and `dict` functions. `dict` converts zip iterator to a dictionary.

In [55]:
stocks = ['Alphabet C', 'VCPlus', 'TCS']  ## create list 'stocks'
prices = [3452, 1127, 2750]  ## create list 'prices'
dictionary = dict(zip(stocks, prices))   ## zip the two lists and convert zip object to a dictionary using dict()
print(dictionary) ## print dictionary {'Alphabet C': 3452, 'VCPlus': 1127, 'TCS': 2750}

{'Alphabet C': 3452, 'VCPlus': 1127, 'TCS': 2750}


To read more on zip built-in function, refer to [documentation](https://docs.python.org/3/library/functions.html#zip) here.

## Matplotlib

[Matplotlib](https://matplotlib.org/) is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [56]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline

### Plotting

The most important function in `matplotlib` is `plot`, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

You can read much more about the `plot` function in the [documentation](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot).

### Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

## Regex

A regular expression (or RE) specifies a set of strings that matches it; the functions in this module let you check if a particular string matches a given regular expression (or if a given regular expression matches a particular string, which comes down to the same thing). Regex may involve metacharaters/Sequences/Sets that form a search pattern.

1. `^` matches the start of the string
2. `*` matches zero or more number of repitions of preceding Regular expression.
3.  `$` matches the end of string with given sequence.
4.  `\d`	Returns a match where the string contains digits (numbers from 0-9)
5.  `\s` returns a match where the string contains a white space character
6.  `[a-n]` returns a match for any lower case character, alphabetically between a and n.
7.  `[0-9]` returns a match for any digit between 0 and 9

Complete list of sequences can be found [here](https://docs.python.org/3/library/re.html)

To use Regex, we first need to import the package.

In [ ]:
import re

This package offers variety of different functions which can be used to find patterns in the string.

###FindAll()
This method is used to print a list of all the matches of given string. If no matches are found then an empty list is returned. Following examples will explain:

In [ ]:
txt = "Its been an energetic day today."
x = re.findall("day", txt) ## find all instances of string 'day' in txt string
print(x) ## print all occurences if exist

In [ ]:
txt = "from"
x = "We are going there tomorrow."
x = re.findall("is", txt) ## find all instances of string 'is' in txt string
print(x) ## print empty string since no such instances exist

### Split()
Split function is used to return a list where there the string has been split at each match. In example below, regular expression `\s` splits the string at each white space character.

In [ ]:
txt = "We are going to a park."
x = re.split("\s", txt)
print(x)


We can control the maximum number of splits by providing `maxsplit` parameter. In example below, only first 2 splits occurences will be found and returned as list.

In [ ]:
txt = "We are going to a park."
x = re.split("\s", txt, 2)
print(x)

### Sub()
The sub() function replaces the matches with the text of your choice. For example, [0-9] regex will replace digits with given string.

In [ ]:
txt = "Some digits like 100 and 490 are replaced."
x = re.sub("[0-9]", "-", txt)
print(x)

### Search()
Returns a Match object if there is a match anywhere in the string.
Using this method, the regular expression in given example looks for any words that starts with an upper case "S":

In [ ]:
txt = "The rain in Spain."
x = re.search(r"\bS\w+", txt)
print(x) ## prints match object
print(x.group()) ## prints a tuple containing all the subgroups of the match,

## Reading from the File

Refer to the dataset `StudentsPerformance.csv` for the question below. Provide the path of this csv to the `read_csv` command.




In [ ]:
import pandas as pd
data = pd.read_csv('Dataset/students data.csv')
data.head()


## Writing to a File

In [ ]:
#open the file in the append mode as the write mode overwrites the first line
file1 = open("myfile.txt","a")
file1.write("Today \n")
file1.close()

## Scikit Learn

Scikit-learn, commonly known as sklearn, is a free Machine Learning library for the Python programming language. It offers numerous classification, regression, and clustering algorithms, including K-Means, Linear Regression, Logistic Regression, Naive Bayes and State Vector Machines, etc. Moreover, it supports tasks such as feature extraction, feature selection, model evaluation, model selection, parameter tuning, etc.

Sklearn is a widely used library due to numerous reasons, such as:

1.   It is easy to learn and use.
2.   It covers all aspects of Machine Learning.
3.   It is very versatile and powerful.
4.   It is very versatile and powerful.
5.   It is an open-source library with an active community and detailed documentation.


More information regarding Sklearn, including its implementation, can be found [here](https://scikit-learn.org/stable/).


## Questions
Solve some of the questions below to get more clear understanding of python basics:

**Q1: Write the code to determine the parity of a given number. It should return `even` or `odd` as a string depending on the parity.**             


In [57]:
def parity(num):
    ...

In [58]:
grader.check("Q01")

Q01 results:
    Q01 - 1 result:
        ❌ Test case failed
        Trying:
            assert parity(3) == 'odd'
        Expecting nothing
        **********************************************************************
        Line 1, in Q01 0
        Failed example:
            assert parity(3) == 'odd'
        Exception raised:
            Traceback (most recent call last):
              File "c:\Anaconda\envs\myenv\Lib\doctest.py", line 1395, in __run
                exec(compile(example.source, filename, "single",
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             compileflags, True), test.globs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<doctest Q01 0[0]>", line 1, in <module>
                assert parity(3) == 'odd'
                       ^^^^^^^^^^^^^^^^^^
            AssertionError
        Trying:
            assert parity(4) == 'even'
        Expecting nothing
        **********************************************************************
        Line 2, in Q01 0
        Failed example:
            assert parity(4) == 'even'
        Exception raised:
            Traceback (most recent call last):
              File "c:\Anaconda\envs\myenv\Lib\doctest.py", line 1395, in __run
                exec(compile(example.source, filename, "single",
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             compileflags, True), test.globs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<doctest Q01 0[1]>", line 1, in <module>
                assert parity(4) == 'even'
                       ^^^^^^^^^^^^^^^^^^^
            AssertionError

**Q2: For a given list of strings, check if the length of the string is even or odd. Store "`even`" or "`odd`" in the variable `list_parity` accordingly.**

In [ ]:
x = ['alphabets', 'numerics', 'data types', '123', 'wild' ,'abc', 'chars']
list_parity = ...

In [ ]:
grader.check("Q02")

**Q3: Write a code to reverse the string "hello" using indexing. Store the reversed string in `output_string`.**

In [ ]:
input_string = "hello"
output_string = ...

In [ ]:
grader.check("Q03")

**Q4: For numbers in range 0 to 100, return a list of those that are multiple of 2 but not 5 using list comprehension. Store it in `result_lc`.**

In [ ]:
result_lc = ...

In [ ]:
grader.check("Q04")

**Q5: Generate two numpy arrays x and y of 20 random integers between [1,10], compute a new array where each element is the square of sum of corresponding entries in x and y. Use broadcasting in this question and store the result in `z`.**

For example: x =[1,2,3] , y =[3,4,5]
Result: [16, 36, 64]

In [ ]:
import numpy as np

x = ...
y = ...

z = ...

In [ ]:
grader.check("Q05")

**Q6: Given two dictionaries of ids and Mathematics scores, write a function to return a default dictionary where keys are students ids and values are a list containing the corresponding student's name and their score. Store the result in `student_dict`.**


In [ ]:
from collections import defaultdict
ids = {4: 'John', 2: 'Robert', 1: 'Alice', 3: 'William', 5: 'Edward'} ## keys are student ids and values are student names
maths_scores = {2: 89, 1: 78.8, 3: 100, 5: 67.5, 4: 45}  ## keys are student ids and values are student scores

def return_dict(ids,maths_scores):
    ...

student_dict = ...

In [ ]:
grader.check("Q06")

**Q7: Given a numpy array `x`, write a function to find all negative elements and replace them with their squares. Use boolean indexing. Store the result in `negative_filtered`.**

In [ ]:
x = np.array([[4,-5,7,-10],[-110,4,-8,34],[14,5,-17,-20]])

def replaceNegative(x):
    ...
    
negative_filtered = ...

In [ ]:
grader.check("Q07")

**Q8: Write a function which takes that numpy 1-D array as input and returns the following:**

1.   Maximum value in the array
2.   Standard Deviation
3.   Sum of all the elements in the array

Store results in `max_val`, `std_dev`, `sum_val`.

In [ ]:
x = np.array([[4,-5,7,-10],[-110,4,-8,34],[14,5,-17,-20]])

def array_info(arr):
    ...

max_val, std_dev, sum_val = ...

In [ ]:
grader.check("Q08")

**Q9: Write a Python function that accepts a string and calculates and returns the number of upper case letters and lower case letters. Store the result in `upper`, `lower` respectively.**  



In [ ]:
str = "Hello Mr. Rogers, how are you this fine Tuesday?"

def count_chars(input_str):
    ...
    
upper, lower = ...

In [ ]:
grader.check("Q09")

**Q10: Write a function that stores the integers from 1 to 100. But for multiples of three, store "Fizz" instead of the number, and for the multiples of five store "Buzz". For numbers which are multiples of both three and five store "FizzBuzz". Store the result in `fizzbuzz`.**

In [ ]:
def fizzbuzz_func():
    ...

fizzbuzz = ...

In [ ]:
grader.check("Q10")

**Q11: Write a function, `calculateSum(l,k)` which will take a list, `l` and a number `k` as input and return two numbers from `l` that add up to `k`.**

In [ ]:
l = [1, 21, 3, 14, 5, 60, 7, 6]
k = 81

def calculateSum(l, k):
    ...
    
num1, num2 = calculateSum(l, k)

In [ ]:
grader.check("Q11")



**Q12: Write a function, `find_students`  that receives the students dictionary and an address, and returns a list with names in sorted order of all students whose address matches the address in the argument. Store the result in `students_list`.**



In [ ]:
def find_students(address, students):
  ...

students = {
      "Ali": {"age": 6, "address": "Lahore"},
      "Ahmad": {"age": 15, "address": "Islamabad"},
      "Eesha": {"age": 21, "address": "Karachi"},
}

students_list = ...

In [ ]:
grader.check("Q12")

**Q13: Edit the following iterator class to return all the positive even numbers from 1 to (n).**   

In [ ]:
class evenNumbers:
  def __init__(self, n):
    ...

  def __iter__(self):
    return self

  def next(self):
    ...

myrange = evenNumbers(10)
next_num = myrange.next()

In [ ]:
grader.check("Q13")

**Q14: Using keys and indexing, grab the 'hello' from the given dictionaries. Store the result in `a1`, `a2`, `a3` respectively.**


In [ ]:
d1 = {'simple_key':'hello'}

d2 = {'k1':{'k2':'hello'}}

d3 = {'k1':[{'nest_key':['this is deep',['hello']]}]}

a1 = ...

a2 = ...

a3 = ...


In [ ]:
grader.check("Q14")

**Q15: Write a python Class that accepts a tuple, has two instance variables, setter and getter methods and also write these methods to compute results accordingly:**

1.   def Addition(tup)
2.   def  Subtraction (tup)
3.   def Multiplication(tup)
4.   def Division(tup )
5.   def Power(tup)


In [ ]:
class HandleTuple:
    def __init__(self, tup):
        self._tup = ...

    # Setter
    def set_tuple(self, tup):
        self._tup = ...

    # Getter
    def get_tuple(self):
        ...

    # 1. Addition
    def Addition(self):
        ...
 
    # 2. Subtraction (first element - rest)
    def Subtraction(self):
        ...

    # 3. Multiplication
    def Multiplication(self):
        ...

    # 4. Division (first element ÷ rest, don't worry about division by zero)
    def Division(self):
        ...

    # 5. Power (first element raised to power of rest sequentially)
    def Power(self):
        ...

tupclass = HandleTuple((10,2,3))
addition = tupclass.Addition()
subtraction = tupclass.Subtraction()
multiplication = tupclass.Multiplication()
division = tupclass.Division()
power = tupclass.Power()

In [ ]:
grader.check("Q15")

<!-- BEGIN QUESTION -->

**Q16. For given array x of floating point numbers. Print plots for the following functions with the specified properties. Make a different subplot for each listed number.**  

1. y1 = $x^{2}$,
y2 = $x^{3}$
* X and Y axis labels
* Legend in top left corner
* Give appropriate title
* y1 line with green color
* y2 line with orange color

2. y1 = $sin(x)^{2}$ * $sin(x)^{3}$
* X and Y axis labels
* Legend in top center
* Give appropriate title
* line fontsize 15

3. y1 = $cos(x)^{2}$
* X and Y axis labels
* Legend in bottom right corner
* Give appropriate title
* y1 graph with green circles only and circles should not be connected via line.



In [ ]:
x = np.arange(-10,10, 0.2)

...

<!-- END QUESTION -->

**Q17: Read the data given in the file `students data` and save it into a dataframe named `students_df`. DO NOT USE ABSOLUTE PATHS.**

**Also, plot the Math, Reading, and Writing Scores along with the name of the student. Make different plots for all three scores.**

Remember to do the following:

1.   Assign X and Y labels
2.   Assign an appropriate title






In [ ]:
file_path = 'Dataset/students data.csv'
students_df = ...

...

In [ ]:
grader.check("Q17")

## Tweets analysis using Regex
Refer to the Twitter US Airline Sentiment dataset for questions 18 to 22 below. We can use the Regex expressions to search for patterns in tweets. Solving some of the questions below can help you in getting better understanding of REGEX.

**Q18. Search for all twitter handles in the tweets. In a tweet all `@sometext` act as the twitter handle - it only contains word characters (letters, numbers, underscores, NO punctuation) . Return a set of all handler. Store the result in `twitter_handles`. Note: A Set doesn't contain duplicates.**  

In [ ]:
twitter_df = pd.read_csv('Dataset/Twitter US Airline Sentiment.csv')

...


In [ ]:
grader.check("Q18")

**Q19: Remove all punctuation marks from the tweets. Create a new column in the `twitter_df` named `cleaned_text` that contains all the cleaned tweets. Punctuation marks include period, comma, semi-colon, exclaimation mark, question mark and semicolon.**

In [ ]:
...

twitter_df['cleaned_text'] = ...

In [ ]:
grader.check("Q19")

**Q20 Return a list of all words that start with either a digit or an upper case alphabet. Store the result in `digit_or_uppercase_words`.**

In [ ]:
...

digit_or_uppercase_words = ...

In [ ]:
grader.check("Q20")

**Q21 Store the top 10 most frequently used hastags(`#`) in all the tweets in descending order (by frequency). Store the result in `top10_hashtags`.**

In [ ]:
...

top10_hashtags = ...


In [ ]:
grader.check("Q21")

**Q22: Remove all urls (starting with http/https) from the `cleaned_text` column and store a list of all URLs in a list named `removed_urls`.**




In [ ]:
removed_urls = []
...
twitter_df['cleaned_text'] = ...

In [ ]:
grader.check("Q22")

## Regex for Urdu

#### Refer to the dataset `UrduWiki.csv` for questions 23 till 25. Provide the utf-8 encoding in `read_csv` to read the dataset correctly as it contains Urdu characters as well:

```
pd.read_csv("UrduWiki.csv", encoding = "utf-8")
```



Solve the questions below to get familiarised with using regex in a multilingual dataset.

**Q23. Search for all the English words in the articles (contains only english alphabets). Return a set of all English words. Store it in a variable `english_words`. Note: A Set doesn't contain duplicates.**

In [ ]:
file_path = "Dataset/UrduWiki.csv"
urdu_df = pd.read_csv(file_path, encoding='utf-8')

...
english_words = list(english_words)

In [ ]:
grader.check("Q23")

**Q24: Replace all the digits with Urdu digits and remove English words. Store this text in a list named `normalized_content`. Urdu digits: [۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹]**

In [ ]:
urdu_digits = {'0': '۰', '1': '۱', '2': '۲', '3': '۳', '4': '۴', '5': '۵', '6': '۶', '7': '۷', '8': '۸', '9': '۹'}

normalized_content = ...
...


In [ ]:
grader.check("Q24")

**Q25: Return the top 10 most frequently used words starting with(م) in all the articles. Store in a list `top10_words` in descending order (by frequency).**

In [ ]:
...
top10_words = ...

In [ ]:
grader.check("Q25")